version: '3.8'
services:
  pg:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=54321
      - POSTGRES_DB=postgres
    volumes:
      - ./base:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always