version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=54321
      - POSTGRES_DB=data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always