"""fix

Revision ID: 78c7a372e851
Revises: 2ab0f1240cd7
Create Date: 2024-12-03 13:41:22.419514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c7a372e851'
down_revision: Union[str, None] = '2ab0f1240cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('attempts', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
