"""add students for class

Revision ID: 896084c49939
Revises: 243ed52bbf5c
Create Date: 2024-11-17 13:32:39.893223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896084c49939'
down_revision: Union[str, None] = '243ed52bbf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('student_ids', sa.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'student_ids')
    # ### end Alembic commands ###
