"""add url for user append

Revision ID: 46de7f997d49
Revises: 896084c49939
Create Date: 2024-11-18 20:35:46.840287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46de7f997d49'
down_revision: Union[str, None] = '896084c49939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('join_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'classes', ['join_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='unique')
    op.drop_column('classes', 'join_code')
    # ### end Alembic commands ###
