"""Initial tables

Revision ID: 243ed52bbf5c
Revises: 
Create Date: 2024-11-16 15:07:16.469869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ed52bbf5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('cl_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('hand_in_by_date', sa.Date(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('multiple_attempts', sa.Boolean(), nullable=True),
    sa.Column('number_of_questions', sa.BigInteger(), nullable=False),
    sa.Column('time_to_answer', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=True),
    sa.Column('last_attempt_time', sa.Date(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('tests')
    op.drop_table('classes')
    # ### end Alembic commands ###
